
spring:
  datasource:
  generate-unique-name: false
  name: tacocloud
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1230648028216677
            client-secret: 536e8c70bdbd782009c2eef63ab63d6e
            scope:
              - email
              - public_profile


logging:
  level:
    org:
      springframework:
        security: WARN
taco:
  orders:
    pageSize: 35

